# Generated by Django 3.2.2 on 2021-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('BK', 'Bakery'), ('PA', 'Pastry'), ('GR', 'Grills'), ('SH', 'Sushi'), ('DR', 'Drinks'), ('OT', 'Others')], max_length=2)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('food_venues', models.ManyToManyField(to='core.FoodVenue')),
            ],
        ),
    ]
