# Generated by Django 3.2.2 on 2021-07-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210712_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpackage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packages',
        ),
        migrations.DeleteModel(
            name='orderItem',
        ),
        migrations.DeleteModel(
            name='orderPackage',
        ),
    ]
