# Generated by Django 3.2.5 on 2021-07-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210712_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpackage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packages',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.package'),
        ),
        migrations.DeleteModel(
            name='orderItem',
        ),
        migrations.DeleteModel(
            name='orderPackage',
        ),
    ]
