# Generated by Django 3.2.2 on 2021-07-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210715_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.package'),
        ),
    ]
