# Generated by Django 3.2.5 on 2021-07-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Bakery', 'Bakery'), ('Pastry', 'Pastry'), ('Deserts', 'Deserts'), ('Sushi', 'Sushi'), ('Beverages', 'Beverages'), ('Others', 'Others')], max_length=15),
        ),
    ]
