# Generated by Django 3.2.2 on 2021-05-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favortie_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favortie_items',
        ),
    ]
