# Generated by Django 3.2.2 on 2021-05-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_prefered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='prefered_by',
        ),
    ]
