# Generated by Django 3.2.2 on 2021-05-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_favortie_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favortie_items',
            new_name='favorite_item',
        ),
    ]
