# Generated by Django 3.2.2 on 2021-05-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_favortie_items_favorite_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favorite_item',
        ),
    ]
