# Generated by Django 3.2.2 on 2021-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_favorite_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorite_by',
            field=models.ManyToManyField(to='core.Customer'),
        ),
    ]
