# Generated by Django 3.2.2 on 2021-05-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_favorite_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(default='', max_length=255)),
                ('favorite_by', models.ManyToManyField(to='core.Customer')),
                ('food_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foodvenue')),
                ('items', models.ManyToManyField(to='core.Item')),
            ],
        ),
    ]
