# Generated by Django 3.2.2 on 2021-06-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210601_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='available_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('date_time', models.DateTimeField()),
                ('food_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foodvenue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
