# Generated by Django 3.2.2 on 2021-07-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_available_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_items',
            name='date_time',
        ),
    ]
