# Generated by Django 3.2.2 on 2021-07-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_available_items_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='available_items',
            new_name='available_item',
        ),
    ]
